services:
  postgres:
    image: postgres:latest
    container_name: cryptocop-postgres
    restart: always
    environment:
      POSTGRES_USER: cryptocop_user
      POSTGRES_PASSWORD: cryptocop_password
      POSTGRES_DB: cryptocop_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cryptocop-rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP protocol (used by API & worker)
      - "15672:15672"   # Management UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  payments-worker:
    build:
      context: .
      dockerfile: Cryptocop.Software.Worker.Payments/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__ExchangeName=cryptocop-exchange
      - RabbitMq__QueueName=payment-queue
      - RabbitMq__RoutingKey=create-order
    restart: always
    email-worker:
      build:
        context: .
        dockerfile: Cryptocop.Software.Worker.Emails/Dockerfile
      depends_on:
        rabbitmq:
          condition: service_healthy
      environment:
        - RabbitMq__HostName=rabbitmq
        - RabbitMq__UserName=guest
        - RabbitMq__Password=guest
        - RabbitMq__ExchangeName=cryptocop-exchange
        - RabbitMq__QueueName=email-queue
        - RabbitMq__RoutingKey=create-order
        - SendGrid__ApiKey=YOUR_SENDGRID_API_KEY
      restart: always
volumes:
  postgres_data:
  rabbitmq_data:
