services:
  postgres:
    image: postgres:latest
    container_name: cryptocop-postgres
    restart: always
    environment:
      POSTGRES_USER: cryptocop_user
      POSTGRES_PASSWORD: cryptocop_password
      POSTGRES_DB: cryptocop_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cryptocop-rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP protocol (used by your API)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
